package io.zkz.mc.gametools.util

import org.bukkit.entity.Entity
import org.bukkit.entity.EntityType.*

fun Entity.isHostile(): Boolean {
    return when (type) {
        ELDER_GUARDIAN, WITHER_SKELETON, STRAY, HUSK, ZOMBIE_VILLAGER, SKELETON_HORSE, ZOMBIE_HORSE, EVOKER, VINDICATOR, ILLUSIONER, CREEPER, SKELETON, SPIDER, GIANT, ZOMBIE, SLIME, GHAST, ZOMBIFIED_PIGLIN, ENDERMAN, CAVE_SPIDER, SILVERFISH, BLAZE, MAGMA_CUBE, WITCH, ENDERMITE, GUARDIAN, SHULKER, PHANTOM, PUFFERFISH, DROWNED, PILLAGER, RAVAGER, HOGLIN, PIGLIN, WARDEN, PIGLIN_BRUTE, ZOGLIN -> true
        else -> false
    }
}
